before_install:
  - git clone --recursive https://github.com/rust-lang/cargo
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq rust-nightly
  - cd cargo && make && sudo make install && cd .. && sudo rm -rf cargo

script:
  - make
  - make test

branches:
  only: master
