before_install:
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq rust-nightly cargo

script:
  - make
  - make test

branches:
  only: master
