before_install:
  - curl -O http://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xf cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq rust-nightly
  - sudo cargo-nightly-x86_64-unknown-linux-gnu/install.sh
  - sudo rm -rf cargo-nightly-x86_64-unknown-linux-gnu

script:
  - make
  - make test

branches:
  only: master
