[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "rustic"
version = "0.0.0"

[dependencies]
env_logger = "*"
log = "*"

[dependencies.lines]
git = "https://github.com/japaric/lines.rs"
